# Generated by Django 5.0.6 on 2024-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BinaryField(max_length=64)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
