# Generated by Django 5.0.6 on 2024-06-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chat_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
